# Generated by Django 2.0.3 on 2018-05-12 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site', '0014_handle_taxes'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='homepage_content',
            field=models.TextField(default='', blank=True),
        ),
    ]
