# Generated by Django 2.0.3 on 2018-05-16 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site', '0014_handle_taxes'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='footer_text',
            field=models.CharField(null=True, blank=True, max_length=800),
        ),
    ]
