# Generated by Django 2.0.3 on 2018-05-17 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site', '0015_sitesettings_footer_text'),
        ('site', '0015_sitesettings_homepage_content'),
    ]

    operations = [
    ]
